### ISSUE TITLE
Linker Error with atlas::utils::join

### ISSUE THREAD

**Issue by SabineWren** [marovira/bsoid#1]
Using Linux 4.15, I tried GCC 4.3, GCC 8.1, and Clang 6.0.0. The compilers all gave the same errors, although the ones I copy-paste here are from Clang.
```
git clone <repo>
cd bsoid
```
changed .gitmodules url to https://github.com/marovira/atlas
```
git submodule init
git submodule update
cd .. && mkdir ./build && cd ./build
cmake ../bsoid
```

got an error 
```
CMake Error: Could not open file for write in copy operation /docs/Doxyfile.tmp
CMake Error: : System Error: No such file or directory
CMake Error at CMakeLists.txt:49 (configure_file):
```

fixed by adding to CMakeLists.txt after line 31:
```
set(BSOID_BINARY_DIR "${PROJECT_BINARY_DIR}")
```

ran make and got an error:
```
bsoid/source/main.cpp:103:32: error: use of undeclared identifier 'TRUE'
```
I changed it from TRUE to true and ran make again:
```
bsoid/polygonizer/uint128_t.hpp:43:30: error: constexpr function
      never produces a constant expression
```
This function calls std::swap, which as of C++20 should work with constexpr. GCC 8.1 has support for at least some of C++20, so I tried hard-coding -std=gnu++2a in the compiler flags (confirmed it added using make VERBOSE=1), but got the same error. I re-cloned and removed the constexpr keyword instead.
Running make again:
```
bsoid/source/bsoid/tree/Node.cpp:29:33: error: no member named 'join' in
      namespace 'atlas::utils'
```
This looks like a linker error. The function's declared in bsoid/lib/atlas/include/atlas/utils/BBox.hpp
and defined in bsoid/lib/atlas/source/atlas/utils/BBox.hpp, so I tried adding to the Node.cpp file:
```
#include <atlas/include/utils/BBox.hpp>
```
That didn't work. I would like to run your polygonizer, so please help.

**Comment by marovira** [comment]
Hi @SabineWren. I'm currently at work but I'll take a look at it as soon as I get home. Thanks for doing most of the legwork here. I've only ever tested this on Windows and while in theory it runs on Linux, I never outright tested it. Just to save you some headaches down the line, Bsoid does require Intel TBB to function (unless you switched out some code) and I have no idea how to make it work on Linux. Just a heads up.

**Comment by marovira** [comment]
@SabineWren I just pushed a few changes. I've included some of the fixes that you mentioned (the one for CMake I can't reproduce), and also tweaked the CMakeLists slightly to expose the fact that TBB is required. As for the linking error for `atlas::utils::join` I can't reproduce that bug on my machine. The inclusion of the header should not matter, since the header is included through the implicit functions header. Can you try a clean build and let me know if this is still happening?

**Comment by SabineWren** [comment]
Thanks for checking. TBB is one of the dependencies I installed:
```
libgl1-mesa-dev
libglu1-mesa-dev
xorg-dev
libtbb-dev
```
My current steps: clone, initialize and update submodule, change BSOID_BUILD_DOCS from ON to OFF, fix a guard typo (see atlas pull request).
```
cmake ../bsoid
make
```
I made several attempts to fix the error I mentioned in my last post:
```
<path-to-bsoid>/source/bsoid/tree/Node.cpp:29:33: error:
    no member named 'join' in namespace 'atlas::utils'
```
Adding #include "BBox.hpp" to the Node.cpp file generates a "file not found error" (as it should) then when I add
```
-I/<path-to-bsoid>/lib/atlas/include/atlas/utils
```
to the compilation, I still get "no member named 'join' in namespace 'atlas::utils'". I tried copy-pasting the entire function definition, and then it gets really strange:
```
<path-to-bsoid>/source/bsoid/tree/Node.cpp:45:20: error:
call to 'join' is ambiguous
    mBox = join(mBox, child->getBBox());

<path-to-bsoid>/lib/atlas/include/atlas/utils/BBox.hpp:29:25: note:
    candidate function
        friend BBox join(BBox const& b1, BBox const& b2);

<path-to-bsoid>/source/bsoid/tree/Node.cpp:27:22: note:
    candidate function
        atlas::utils::BBox join(atlas::utils::BBox const& b1, at...
```
We can see that it can find the right function! Therefore, it should link just fine, so I guess it isn't a linker problem. Maybe it's something with C++ namespaces?

**Comment by marovira** [comment]
I seriously don't understand what's going on, but I have a way of fixing it. Given that the members of the `BBox` class are public, the usage of `friend` is superfluous. Try this: in `BBox.hpp` move the declaration of `join` to outside the class, after line 32. Remove the `friend` keyword and leave the rest as is. See if that works.

**Comment by SabineWren** [comment]
Thanks, that worked. I got it building (albeit with many compiler warnings), but when running normally it crashes instantly with a core dump. With valgrind, it loads to a GUI (heisenbug). I can hopefully figure it out from here, and I'll make some pull requests as I fix things.

**Comment by marovira** [comment]
Sounds good. Let me know if you need any help!
